#!/usr/bin/env python3
"""LinkedIn AI News Post — multi-agent pipeline.

Flow: analytics update → load blog archive (articles.json) → filter out already-published
      → pick random article → write post → publish LinkedIn → notify Telegram.

Source of truth: site/articles.json, the AI Architect blog's append-only archive,
generated by site_pipeline.py. LinkedIn posts always link back to Luca's own blog article.
"""

import argparse
import json
import logging
import os
import random
import re
import sys
from datetime import datetime, timezone
from pathlib import Path
from urllib.parse import parse_qsl, urlencode, urlsplit, urlunsplit

import anthropic

from agents.analytics_agent import update_analytics
from agents.carousel_agent import create_carousel
from agents.notifier_agent import request_approval, send as notify
from agents.publisher_agent import publish, publish_carousel, publish_text
from agents.writer_agent import check_human_voice, critique_post, truncate_comment, write_post
from config import (
    ARTICLES_JSON_PATH, CHANGELOG_SOURCE_HOMEPAGES, NEWSLETTER_URL, POSTS_DIR, UTM_MEDIUM, UTM_SOURCE,
)
from utils.history import commit_history_to_git, extract_hashtags, extract_topics, load_history, save_history
from utils.og_meta import fetch_og_meta
from utils.page_scraper import fetch_page_text
from utils.url_utils import is_valid_url, normalize_url

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s %(levelname)s %(message)s",
    datefmt="%Y-%m-%dT%H:%M:%S",
)
log = logging.getLogger(__name__)


def _load_env() -> None:
    env_file = Path(__file__).parent / ".env"
    if not env_file.exists():
        return
    log.info("Loading .env file")
    with open(env_file) as f:
        for line in f:
            line = line.strip()
            if not line or line.startswith("#"):
                continue
            line = line.removeprefix("export ").strip()
            key, _, val = line.partition("=")
            os.environ[key.strip()] = val.strip('"').strip("'")


def _require_env(*keys: str) -> None:
    missing = [k for k in keys if not os.environ.get(k)]
    if missing:
        log.error("Missing environment variables: %s", ", ".join(missing))
        sys.exit(1)


def _strip_html(html: str) -> str:
    return re.sub(r"\s+", " ", re.sub(r"<[^>]+>", " ", html or "")).strip()


def _extract_article_content(article: dict) -> tuple[str, list[str]]:
    """Returns (plain-text body for LinkedIn context, diagram image paths for carousel reuse).

    Handles both the current block-based article schema and the older fixed-field schema
    (articles published before the block-based rewrite — never rewritten once published, so
    both shapes coexist in the archive forever). Only prose/callout/quote text is ever used
    for the LinkedIn body — never raw code or diagram data, which would degrade the post.
    """
    if "blocks" in article:
        body_parts = []
        diagram_images = []
        for b in article["blocks"]:
            btype = b.get("type")
            if btype in ("prose", "callout"):
                body_parts.append(_strip_html(b.get("html", "")))
            elif btype == "quote":
                body_parts.append(b.get("text", ""))
            elif btype == "diagram" and b.get("image"):
                diagram_images.append(str(POSTS_DIR / "images" / b["image"]))
        return " ".join(p for p in body_parts if p).strip(), diagram_images

    # Legacy fixed-field schema (articles published before the block-based rewrite)
    body = _strip_html(article.get("body_html", "")) + " " + _strip_html(article.get("how_i_use_it", ""))
    diagram_images = [
        str(POSTS_DIR / "images" / d["image"])
        for d in article.get("diagrams", [])
        if d.get("image")
    ]
    return body.strip(), diagram_images


def _load_blog_articles(published_urls: set[str]) -> list[dict]:
    """Load articles from the AI Architect blog archive, filter out already-published ones.

    Each blog article becomes a LinkedIn post candidate that links back to its own
    permalink page on the blog — never to a third-party URL.
    """
    path = Path(ARTICLES_JSON_PATH)
    if not path.exists():
        log.error("articles.json not found at %s — run site_pipeline.py first", path)
        return []

    with open(path, encoding="utf-8") as f:
        articles = json.load(f)

    log.info("articles.json loaded: %d articles", len(articles))

    candidates = []
    for a in articles:
        url = normalize_url(f"{NEWSLETTER_URL}/posts/{a['slug']}.html")
        if url in published_urls:
            continue
        body, diagram_images = _extract_article_content(a)
        og_image = a.get("og_image")
        candidates.append({
            "title": a.get("title", ""),
            "url": url,
            "source": "The AI Architect (my blog)",
            "summary": a.get("dek", ""),
            "body": body,
            "technique": a.get("technique", ""),
            "diagram_images": diagram_images,
            # Blog-generated hero image (utils/diagram_renderer.render_hero_image), if this
            # article has one — reused as the LinkedIn thumbnail so _build_og() doesn't
            # scrape the permalink page for an og:image we already rendered ourselves.
            "og_image": f"{NEWSLETTER_URL}/posts/images/{og_image}" if og_image else None,
        })

    log.info("After dedup filter: %d fresh articles", len(candidates))
    return candidates


def _pick_random_story(stories: list[dict]) -> dict | None:
    """Pick a random article from the blog — every run promotes a different article."""
    if not stories:
        return None
    picked = random.choice(stories)
    log.info("Random pick: technique=%s title=%s", picked.get("technique"), picked.get("title"))
    return picked


def _build_og(story: dict) -> dict:
    """Return OG dict with guaranteed image attempt.

    Priority: cached og_image → live fetch from article → source homepage fallback.
    """
    cached = story.get("og_image")
    if cached:
        return {"image": cached}

    log.info("No cached og_image for '%s' — fetching live", story.get("title"))
    og = fetch_og_meta(story.get("url", ""))
    if og.get("image"):
        return og

    source = story.get("source", "")
    fallback_url = CHANGELOG_SOURCE_HOMEPAGES.get(source)
    if fallback_url:
        log.info("No image from article — trying homepage fallback for source '%s'", source)
        og_fallback = fetch_og_meta(fallback_url)
        if og_fallback.get("image"):
            return og_fallback

    log.warning("No og:image found for '%s' (source: %s) — post will have no thumbnail", story.get("title"), source)
    return og


def _notify_analytics_digest(records: list[tuple[str, dict]], tg_token: str, tg_chat: str) -> None:
    """Telegram summary of LinkedIn engagement metrics that just entered history.json this
    run (agents.analytics_agent.update_analytics only fetches once, 7-21 days after a post
    goes live) — this data was silently persisted and never shown to a human before."""
    lines = ["<b>\U0001f4ca LinkedIn Analytics Update</b>\n"]
    for post_id, rec in records:
        a = rec["analytics"]
        lines.append(
            f"\U0001f4cc <b>{rec.get('article_title', post_id)}</b>\n"
            f"   \U0001f44d {a['reactions']}  \U0001f4ac {a['comments']}  "
            f"\U0001f501 {a['reposts']}  \U0001f441 {a['impressions']}  "
            f"(score: {a['engagement_score']})\n"
        )
    notify("\n".join(lines), tg_token, tg_chat)


def _build_post(story: dict, client: anthropic.Anthropic) -> str | None:
    """Write post + critique loop. Returns final comment or None on failure."""
    original = {
        "source": story.get("source", ""),
        "summary": story.get("summary", ""),
    }
    comment = write_post(story, original, client)
    if not comment:
        log.warning("write_post failed")
        return None

    for attempt in range(2):
        critique = critique_post(comment, client)
        c_score = critique.get("score", 10)
        humanness = check_human_voice(comment, client)
        h_score = humanness.get("human_score", 10)
        log.info(
            "Critic attempt=%d score=%d issues=%s | human_score=%d verdict=%s tells=%s",
            attempt + 1, c_score, critique.get("issues", []),
            h_score, humanness.get("verdict"), humanness.get("tells", []),
        )
        if c_score >= 7 and h_score >= 6:
            break
        if attempt == 0:
            log.warning(
                "Critic score=%d human_score=%d — retrying post generation", c_score, h_score
            )
            retry = write_post(story, original, client)
            if retry:
                comment = retry

    return truncate_comment(comment)


def _append_reference_link(comment: str, url: str) -> str:
    """Insert a reference link before the hashtag line(s).

    "text" and "carousel" posts don't get LinkedIn's automatic article link card (only the
    default "article" post type does), so without this the post never points back to the
    blog article at all — just a PDF or plain text floating with no source.
    """
    if not url:
        return comment
    label = "Full breakdown on my blog" if url.startswith(NEWSLETTER_URL) else "Source"
    lines = comment.split("\n")
    hashtag_idx = next((i for i, l in enumerate(lines) if l.strip().startswith("#")), len(lines))
    before = lines[:hashtag_idx]
    while before and not before[-1].strip():
        before.pop()
    after = lines[hashtag_idx:]
    return "\n".join(before + ["", f"{label}: {url}", ""] + after)


def _slug_from_url(url: str) -> str:
    return Path(urlsplit(url).path).stem


def _add_utm_params(url: str, campaign: str) -> str:
    """Tag the outbound LinkedIn link with UTM params so Vercel Analytics can attribute blog
    traffic to this specific post. Applied ONLY to the URL sent to LinkedIn — never to
    story["url"]/history.json's article_url, which must stay the clean canonical permalink
    used for the "already published" dedup check in _load_blog_articles()."""
    if not url:
        return url
    parts = urlsplit(url)
    query = dict(parse_qsl(parts.query))
    query.update({"utm_source": UTM_SOURCE, "utm_medium": UTM_MEDIUM, "utm_campaign": campaign})
    return urlunsplit(parts._replace(query=urlencode(query)))


def _publish_by_type(
    post_type: str,
    comment: str,
    story: dict,
    client: anthropic.Anthropic,
    person_id: str,
    token: str,
) -> str | None:
    """Route to the correct LinkedIn publish function. Returns post_id or None on failure."""
    url = story.get("url", "")
    # Only tag our own blog links — _run_url_pipeline()'s direct "--topic <external-url>" mode
    # posts about a third-party URL we don't own, where UTM params wouldn't make sense.
    tagged_url = _add_utm_params(url, _slug_from_url(url)) if url.startswith(NEWSLETTER_URL) else url

    if post_type == "text":
        return publish_text(_append_reference_link(comment, tagged_url), person_id, token)

    if post_type == "carousel":
        carousel_result = create_carousel(story, client, person_id, token)
        if not carousel_result:
            log.error("Carousel creation failed — aborting publish")
            return None
        document_urn, carousel_comment = carousel_result
        carousel_comment = _append_reference_link(carousel_comment, tagged_url)
        return publish_carousel(carousel_comment, document_urn, story["title"], person_id, token)

    # Default: "article" — links to the specific blog permalink, not just the site root
    return publish(comment, tagged_url or NEWSLETTER_URL, story["title"], person_id, token, og=story.get("og"))


def _run_url_pipeline(
    url: str,
    skip_confirm: bool,
    post_type: str,
    client: anthropic.Anthropic,
    tg_token: str,
    tg_chat: str,
    token: str,
    person_id: str,
    history: dict,
) -> None:
    """Direct article pipeline: fetch URL → write post → publish. No feed/ranking."""
    url = normalize_url(url)
    if not is_valid_url(url):
        log.error("Invalid URL for direct pipeline: %s", url)
        notify(f"❌ URL non valido per il pipeline diretto: {url}", tg_token, tg_chat)
        sys.exit(1)

    log.info("Direct URL pipeline: %s (post_type=%s)", url, post_type)

    og = fetch_og_meta(url)
    title = og.get("description") or url
    body = fetch_page_text(url)

    if not body:
        log.warning("Could not fetch article body from %s — proceeding with OG description only", url)

    story = {
        "url": url,
        "title": title,
        "source": url.split("/")[2],  # hostname as source
        "body": body,
        "og": og,
    }

    comment = _build_post(story, client)
    if not comment:
        notify("❌ write_post fallito nel pipeline diretto.", tg_token, tg_chat)
        sys.exit(1)

    if not skip_confirm:
        preview = (
            f"<b>\U0001f4dd Post da pubblicare su LinkedIn</b>\n\n"
            f"<b>{title}</b>\n"
            f"\U0001f517 {url}\n\n"
            f"<i>{comment}</i>"
        )
        approved = request_approval(preview, tg_token, tg_chat)
        if not approved:
            notify("⏭ Post annullato o timeout — nessuna pubblicazione.", tg_token, tg_chat)
            log.info("Post not approved — skipping LinkedIn publication")
            return

    post_id = _publish_by_type(post_type, comment, story, client, person_id, token)
    if not post_id:
        notify("❌ Pubblicazione fallita nel pipeline diretto.", tg_token, tg_chat)
        sys.exit(1)

    history[post_id] = {
        "post_id":       post_id,
        "published_at":  datetime.now(timezone.utc).isoformat(),
        "article_url":   url,
        "article_title": title,
        "source":        story["source"],
        "score":         None,
        "post_type":     post_type,
        "comment_text":  comment,
        "topics":        extract_topics(title, comment),
        "hashtags":      extract_hashtags(comment),
        "analytics":     None,
    }
    save_history(history)
    commit_history_to_git()

    notify(
        "✅ <b>LinkedIn post pubblicato!</b>\n\n"
        f"\U0001f4cc <b>{title}</b>\n"
        f"\U0001f517 {url}\n\n"
        f"\U0001f4ac <i>{comment}</i>\n\n"
        f"\U0001f194 Post ID: {post_id}",
        tg_token, tg_chat,
    )
    log.info("Direct URL pipeline completed successfully")


def main() -> None:
    _load_env()
    _require_env(
        "LINKEDIN_ACCESS_TOKEN",
        "LINKEDIN_PERSON_ID",
        "TELEGRAM_BOT_TOKEN",
        "TELEGRAM_CHAT_ID",
        "ANTHROPIC_API_KEY",
    )

    parser = argparse.ArgumentParser(description="LinkedIn AI News Post")
    parser.add_argument("--no-confirm", action="store_true", help="Skip Telegram approval")
    parser.add_argument("--topic", default="", help="URL to write about directly (skips feed/ranking)")
    parser.add_argument(
        "--post-type",
        choices=["article", "text", "carousel"],
        default="",
        help="LinkedIn post format: article (default), text (no link card), carousel (PDF document)",
    )
    args = parser.parse_args()

    skip_confirm = args.no_confirm or os.environ.get("SKIP_CONFIRM") == "1"
    post_type = args.post_type or os.environ.get("POST_TYPE", "article")

    tg_token  = os.environ["TELEGRAM_BOT_TOKEN"]
    tg_chat   = os.environ["TELEGRAM_CHAT_ID"]
    token     = os.environ["LINKEDIN_ACCESS_TOKEN"]
    person_id = os.environ["LINKEDIN_PERSON_ID"]
    client    = anthropic.Anthropic(api_key=os.environ["ANTHROPIC_API_KEY"])

    # Analytics update (best-effort)
    history = load_history()
    ids_before = {pid for pid, rec in history.items() if rec.get("analytics") is not None}
    history = update_analytics(history, token)
    save_history(history)
    newly_analyzed = [
        (pid, rec) for pid, rec in history.items()
        if rec.get("analytics") is not None and pid not in ids_before
    ]
    if newly_analyzed:
        _notify_analytics_digest(newly_analyzed, tg_token, tg_chat)

    # Direct URL mode: bypass feed/ranking entirely
    topic = args.topic.strip() or os.environ.get("TOPIC", "").strip()
    if topic.startswith("http://") or topic.startswith("https://"):
        try:
            _run_url_pipeline(topic, skip_confirm, post_type, client, tg_token, tg_chat, token, person_id, history)
        except Exception as exc:
            log.exception("Direct URL pipeline failed")
            notify(f"❌ <b>AI LinkedIn Post FAILED</b>\n\n{exc}", tg_token, tg_chat)
            sys.exit(1)
        return

    published_urls: set[str] = set()
    if history:
        published_urls = {normalize_url(r["article_url"]) for r in history.values() if r.get("article_url")}
        log.info("Dedup filter: %d already-published URLs", len(published_urls))

    try:
        # Load blog articles not yet promoted to LinkedIn
        stories = _load_blog_articles(published_urls)

        if not stories:
            notify(
                "<b>AI LinkedIn Post</b>: nessun articolo disponibile in articles.json — "
                "tutti già pubblicati su LinkedIn. Esegui site_pipeline.py.",
                tg_token, tg_chat,
            )
            log.info("No fresh blog articles — skipping LinkedIn post.")
            return

        # Pick a random article from the blog
        story = _pick_random_story(stories)
        if not story:
            log.info("No stories available — skipping.")
            return

        url = normalize_url(story.get("url", ""))
        if not is_valid_url(url):
            log.warning("Invalid URL '%s' — aborting", url)
            return
        story["url"] = url

        # OG metadata (fetched live from the blog permalink — optional, no skip if missing)
        story["og"] = _build_og(story)

        # Write the LinkedIn post (used for article/text; carousel generates its own commentary)
        comment = _build_post(story, client)
        if not comment:
            return

        log.info("Publishing: %s (technique=%s, post_type=%s)", story["title"], story.get("technique"), post_type)

        # Telegram approval
        if not skip_confirm:
            preview = (
                f"<b>\U0001f4dd Post da pubblicare su LinkedIn</b>\n\n"
                f"<b>{story['title']}</b>\n"
                f"\U0001f3f7 {story.get('technique', '')}\n"
                f"\U0001f517 {story['url']}\n\n"
                f"<i>{comment}</i>"
            )
            approved = request_approval(preview, tg_token, tg_chat)
            if not approved:
                notify("⏭ Post annullato o timeout — nessuna pubblicazione.", tg_token, tg_chat)
                log.info("Post not approved — skipping LinkedIn publication")
                return

        post_id = _publish_by_type(post_type, comment, story, client, person_id, token)
        if not post_id:
            notify("❌ Pubblicazione fallita.", tg_token, tg_chat)
            return

        history[post_id] = {
            "post_id":       post_id,
            "published_at":  datetime.now(timezone.utc).isoformat(),
            "article_url":   story["url"],
            "article_title": story["title"],
            "source":        story.get("source", ""),
            "score":         None,
            "post_type":     post_type,
            "comment_text":  comment,
            "topics":        extract_topics(story["title"], comment),
            "hashtags":      extract_hashtags(comment),
            "analytics":     None,
        }
        save_history(history)
        commit_history_to_git()

        notify(
            "✅ <b>LinkedIn post pubblicato!</b>\n\n"
            f"\U0001f4cc <b>{story['title']}</b>\n"
            f"\U0001f3f7 {story.get('technique', '')}\n"
            f"\U0001f517 {story['url']}\n\n"
            f"\U0001f4ac <i>{comment}</i>\n\n"
            f"\U0001f194 Post ID: {post_id}",
            tg_token, tg_chat,
        )
        log.info("Pipeline completed successfully")

    except Exception as exc:
        log.exception("Pipeline failed")
        notify(f"❌ <b>AI LinkedIn Post FAILED</b>\n\n{exc}", tg_token, tg_chat)
        sys.exit(1)


if __name__ == "__main__":
    main()
