import json
import logging
import re

import anthropic

from config import BANNED_WORDS

log = logging.getLogger(__name__)

_WRITER_SYSTEM = """\
Write a LinkedIn post for Luca La Malfa, an AI Architect advising enterprises in Switzerland and Europe.
Primary audience: CTOs, Heads of Innovation, CEOs — decision-makers evaluating or scaling AI.

GOAL: make an executive think "this person understands my problem" or "I need to follow this person" —
and, just as important, make it unmistakably human. Not a well-behaved AI summary of a topic.

HOW HUMANS ACTUALLY WRITE (do this, don't just describe it):
  - Uneven rhythm. A short punch. Then a longer, winding thought that runs on a bit before it lands.
  - Both fast and slow thinking, in the same post: a gut reaction sitting right next to a considered second thought.
  - Real contrast — "but", "except", "and yet" — let one sentence push back on the one before it.
  - A specific, almost private detail beats a generic claim: a real project, a real client conversation, an oddly
    specific number. Vague enthusiasm is the tell of a machine.
  - Take a side. If something is overhyped, say so. If a popular opinion is wrong, say that too. Don't hedge every
    claim into mush.
  - Emotion is allowed and wanted: frustration, mild sarcasm, real excitement, doubt. Flat and neutral is the
    failure mode, not the safe choice.
  - Do NOT visibly follow a template (hook / three parallel points / neat takeaway), as if filling in a form.
    Vary the shape post to post — sometimes lead with the opinion, sometimes with the scene, sometimes with
    the question. Break a "rule of three" on purpose now and then.

STILL REQUIRED (non-negotiable constraints — obey them, but in the human voice described above):
  ≤6 short lines of content before the hashtags (LinkedIn post — must stay scannable on mobile).
  At most one emoji, placed where a person would actually drop it — never decorative.
  No URL in the text — it's attached as a link card automatically.
  No numbered lists, no "Here's why:" breakdowns, no generic call-to-action line.
  End on something that invites a real reply — an opinion worth pushing back on, or a question the reader
    actually has to sit with — not a generic "What do you think?"
  2-3 hashtags, at least one of: #AIStrategy #EnterpriseAI #AIArchitecture #DigitalTransformation
  Banned words (these read as AI tells — never use them): """ + ", ".join(BANNED_WORDS) + """

Voice: a practitioner with opinions who isn't afraid of them. Direct, occasionally over the line, willing to be
contrarian. Should read like it was typed mid-thought by a person, not assembled from a template.

Return ONLY valid JSON: {"comment": "<post text with \\n for line breaks>"}
"""

_CRITIC_SYSTEM = """\
You are a strict LinkedIn post quality checker for an AI Architect targeting C-suite executives.
Return valid JSON only — no markdown fences.

Score a LinkedIn post 0-10: {"score": N, "issues": [...]}

Criteria:
  Hook (2pts): ≤8 words, speaks to a business pain or executive fear — NOT a tech curiosity
  Business angle (2pts): contains a concrete enterprise implication (cost, speed, risk, competitive) — not just a tech fact
  Field credibility (2pts): includes a first-person practitioner signal ("we see", "in client projects", "every architecture review")
  Question (2pts): an executive would genuinely wrestle with it about their own org — NOT "What do you think?" or similar
  Banned words (1pt): none of: """ + ", ".join(BANNED_WORDS) + """
  Tone (1pt): natural, not AI-sounding, no URL in text, no call-to-action phrase\
"""

_HUMANNESS_SYSTEM = """\
You are a skeptical reader trying to catch whether a LinkedIn post was written by a human or generated by an AI.
You have seen thousands of AI-generated LinkedIn posts and know the tells: uniform sentence rhythm, every claim
hedged into mush, a visible hook/body/takeaway template, forced rule-of-three lists, generic upbeat conclusions,
no real opinion, no friction, no specific detail — just smooth, safe, well-behaved prose.

Return valid JSON only — no markdown fences: {"verdict": "human" | "ai", "human_score": N, "tells": ["..."]}

human_score (0-10): 0 = obviously AI-written, 10 = indistinguishable from a real person's unpolished post.
Be strict — generic, evenly-paced, hedge-everything writing should score below 6 even if it is well-written.
"tells" lists the specific things that gave it away (empty list if genuinely human-sounding).\
"""


def _strip_json_fences(text: str) -> str:
    text = re.sub(r"^```(?:json)?\s*", "", text.strip())
    return re.sub(r"\s*```$", "", text)


def write_post(story: dict, original: dict | None, client: anthropic.Anthropic) -> str | None:
    """Generate LinkedIn post text via Claude Sonnet. Returns comment string or None."""
    summary = (original.get("summary") or "")[:300] if original else ""
    source = original.get("source", "") if original else ""
    body = (story.get("body") or "")[:2000]

    content_section = f"Article content:\n{body}\n\n" if body else f"Summary: {summary}\n\n"

    user = (
        f"Story: {story['title']}\n"
        f"Source: {source}\n"
        f"{content_section}"
        "Example of a good hook: \"OpenAI just killed the fine-tuning excuse.\"\n"
        "Example of a good question: \"Which part of your stack breaks first when agents start writing agents?\"\n\n"
        "Do NOT include the URL — it is attached as a link card automatically.\n\n"
        'Return: {"comment": "<HOOK\\n\\nBODY\\n\\nTAKEAWAY\\nQUESTION\\n\\nHASHTAGS>"}'
    )
    msg = client.messages.create(
        model="claude-sonnet-4-6",
        max_tokens=400,
        temperature=0.7,
        system=[{"type": "text", "text": _WRITER_SYSTEM, "cache_control": {"type": "ephemeral"}}],
        messages=[{"role": "user", "content": user}],
    )
    raw = _strip_json_fences(msg.content[0].text)
    log.debug("Writing raw: %s", raw)
    try:
        return json.loads(raw).get("comment") or None
    except json.JSONDecodeError:
        log.error("Writing LLM returned invalid JSON: %s", raw)
        return None


def critique_post(comment: str, client: anthropic.Anthropic) -> dict:
    """Score the post via Claude Haiku. Returns {"score": int, "issues": list[str]}."""
    msg = client.messages.create(
        model="claude-haiku-4-5-20251001",
        max_tokens=150,
        temperature=0,
        system=_CRITIC_SYSTEM,
        messages=[{"role": "user", "content": f"POST:\n{comment}"}],
    )
    raw = _strip_json_fences(msg.content[0].text)
    try:
        return json.loads(raw)
    except json.JSONDecodeError:
        log.warning("Critic returned invalid JSON: %s — assuming OK", raw)
        return {"score": 10, "issues": []}


def check_human_voice(comment: str, client: anthropic.Anthropic) -> dict:
    """Score whether the post reads as human- or AI-written. Returns
    {"verdict": "human"|"ai", "human_score": int, "tells": list[str]}."""
    msg = client.messages.create(
        model="claude-haiku-4-5-20251001",
        max_tokens=200,
        temperature=0,
        system=_HUMANNESS_SYSTEM,
        messages=[{"role": "user", "content": f"POST:\n{comment}"}],
    )
    raw = _strip_json_fences(msg.content[0].text)
    try:
        return json.loads(raw)
    except json.JSONDecodeError:
        log.warning("Humanness checker returned invalid JSON: %s — assuming human", raw)
        return {"verdict": "human", "human_score": 10, "tells": []}


def truncate_comment(comment: str) -> str:
    """Hard-cap to 6 non-hashtag lines + hashtag line."""
    lines = comment.split("\n")
    content_lines = [l for l in lines if not l.strip().startswith("#")]
    hashtag_lines = [l for l in lines if l.strip().startswith("#")]
    if len(content_lines) > 6:
        log.warning("Comment exceeded 6 content lines (%d) — truncating", len(content_lines))
        content_lines = content_lines[:6]
    return "\n".join(content_lines + hashtag_lines)
